* Introduction: Statistics Fundamentals Part II
** Discover what you will learn in Statistics Fundamentals Part II
The ‘Science’ part of Data Science comes from using the scientific method to get results. A lot of what Data Scientists do is conduct experiments with data that already exists. This presents some unique challenges compared to creating a completely new data set.

For starters, the data might not address exactly what you want it to, it might be incidental data from multiple sources that you have to reconcile. Whatever the case may be, it’s the responsibility of the Data Scientist to still analyze that data with the same rigor as they might analyze the results of a lab experiment.

This mostly comes down to testing hypotheses and designing experiments. Sometimes those experiments are in the shape of A/B tests - like when evaluating two variables. Sometimes they are testing the strength of a relationship between two variables.

Though you’ve had an introduction to Hypothesis testing already, to work as an Inferential or Machine Learning Data Scientist, we will go a little deeper to develop a more sophisticated toolset in this area.

** What will Statistics Fundamentals Part II cover?
- Test the strength of an association between two variables
- Design experiments
- Conduct A/B Tests
- Calculate the necessary sample size for an experiment
- Apply your hypothesis testing skills to new projects

** Why did we build this?
To make claims about data, you need statistics to back you up. This unit will equip you with everything you need to make reliable claims about data.

* Hypothesis Testing

** Associations
In this lesson, we’ll use hypothesis tests to make inference about population-level associations between two variables.

We will cover four different hypothesis tests:
- Two Sample T-Tests (for an association between a quantitative variable and a binary categorical variable)
- ANOVA and Tukey Tests (for an association between a quantitative variable and a non-binary categorical variable)
- Chi-Square Tests (for an association between two categorical variables)

*** Two-Sample T-Test
Suppose that a company is considering a new color-scheme for their website. They think that visitors will spend more time on the site if it is brightly colored. To test this theory, the company shows the old and new versions of the website to 50 site visitors, each — and finds that, on average, visitors spent 2 minutes longer on the new version compared to the old. Will this be true of future visitors as well? Or could this have happened by random chance among the 100 people in this sample?

One way of testing this is with a 2-sample t-test. The null hypothesis for this test is that average length of a visit does not differ based on the color of the website. In other words, if we could observe all site visitors in two alternate universes (one where they see each version of the site), the average visiting times in these universes would be equal.

We can use SciPy’s ~ttest_ind()~ function to perform a 2-sample t-test. It takes the values for each group as inputs and returns the t-statistic (not covered in this course) and a p-value:

#+begin_src python
from scipy.stats import ttest_ind
tstat, pval = ttest_ind(times_version1, times_version2)
#+end_src

By default, ~ttest_ind()~ runs a two-sided test.

**** Instructions
***** Task 1
The company randomly sampled 100 site visitors. They showed the old version of their website to half of their sample and the new version to the other half. The amount of time (in minutes) that each visitor spent on the website was recorded.

An overlaid histogram showing the amount of time spent on the website by visitors to the new and old versions has already been created for you in script.py. Press “Run” and inspect the histograms. Based on this picture, do you think there is a significant association between the version of the website a visitor saw and how long they spent on the site?

#+begin_src python
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
data = pd.read_csv('version_time.csv')

#separate out times for  two versions
old = data.time_minutes[data.version=='old']
new = data.time_minutes[data.version=='new']

#run the t-test here:


#determine significance
significant = None

#plot overlapping histograms
plt.hist(old, alpha=.8, label='old')
plt.hist(new, alpha=.8, label='new')
plt.legend()
plt.show()
#+end_src

#+RESULTS:
: None

***** Task 2
The data from this study has already been saved for you in script.py: the time spent by the 50 visitors to the old version is saved as ~old~; the time spent by visitors to the new version is saved as ~new~. Run a two-sample t-test comparing these groups and save the p-value as ~pval~, then print it out.

#+begin_src python :results output
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
data = pd.read_csv('version_time.csv')

#separate out times for  two versions
old = data.time_minutes[data.version=='old']
new = data.time_minutes[data.version=='new']

#run the t-test here:
tstat, pval = ttest_ind(old, new)
print(pval)

#determine significance
significant = None

#plot overlapping histograms
plt.hist(old, alpha=.8, label='old')
plt.hist(new, alpha=.8, label='new')
plt.legend()
plt.show()

#+end_src

#+RESULTS:
: 0.0020408264429904

***** Task 3
Using a significance threshold of 0.05, is there a significant difference between the average amount of time visitors are spending on the old and new versions of the website? In script.py set the value of ~significant~ equal to ~True~ if there is a significant difference and ~False~ if not.

#+begin_src python :results output
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
data = pd.read_csv('version_time.csv')

#separate out times for  two versions
old = data.time_minutes[data.version=='old']
new = data.time_minutes[data.version=='new']

#run the t-test here:
tstat, pval = ttest_ind(old, new)
print(pval)

#determine significance
significant = True

#plot overlapping histograms
plt.hist(old, alpha=.8, label='old')
plt.hist(new, alpha=.8, label='new')
plt.legend()
plt.show()

#+end_src

#+RESULTS:
: 0.0020408264429904

If the p-value is less than 0.05, we can conclude there is a significant difference.

*** Multiple Test
In the previous exercise, we used a two-sample t-test to investigate an association between a quantitative variable (time spent on a website) and a binary categorical variable (an old color scheme or a new color scheme).

In some circumstances, we might instead care about an association between a quantitative variable and a non-binary categorical variable (non-binary means more than two categories).

For example, suppose that we own a chain of stores that sell ants, called VeryAnts. There are three different locations: A, B, and C. We want to know whether customers are spending a significantly different amount per order at any of the locations.

There are three different comparisons we could make: A vs. B, B vs. C, and A vs. C. One way to answer our question is to simply run three separate 2-sample t-tests.

**** Instructions
***** Task 1
We have created samples a, b, and c, representing the amount (in U.S.D) spent on orders at VeryAnts at locations A, B, and C, respectively. We want to see if there’s a significant difference in the average spending per order at the three locations.

Code has been provided for you to generate side by side box plots of the sales at each of these stores. Based on this visualization, are there any stores where customers appear to be spending more or less money?

#+begin_quote
*Hint*

It looks like the largest difference is between stores A and B (the orange box is clearly higher than the blue box). For the other comparisons (A vs. C and B vs. C), it’s a little harder to tell.
#+end_quote

***** Task 2
- Perform a 2-Sample T-test between each pair of location data.

- Store the p-values in variables called ~a_b_pval~, ~a_c_pval~, and ~b_c_pval~. Print them to the console.

- Note that you may see numbers in scientific notation in the print out of one or more p-values. If you see something like e-05 at the end of a number, that means that the preceding number is multiplied by 10^(-5). In other words, 2.5134230524e-05 is equal to 0.000025134230524.

***** Task 3
Inspect the p-values that you printed out. Using a significance level of 0.05, for which pairs of stores did you find a significant difference between the average sale price? Assign the values of ~a_b_significant~, ~a_c_significant~, ~b_c_significant~ to ~True~ if the p-value indicates a significant difference and ~False~ if the p-value does not indicate a significant difference.

*** ANOVA
In the last exercise, we ran three separate 2-sample t-tests to investigate an association between a quantitative variable (amount spent per sale) and a non-binary categorical variable (location of VeryAnts visited, with options A, B, and C). The problem with this approach is that it inflates our probability of a type I error; the more tests we run, the worse the problem becomes!

In this situation, one approach is to instead use ANOVA (Analysis of Variance). ANOVA tests the null hypothesis that all groups have the same population mean (eg., the true average price of a sale is the same at every location of VeryAnts).

In Python, we can use the SciPy function f_oneway() to perform an ANOVA. f_oneway() has two outputs: the F-statistic (not covered in this course) and the p-value. If we were comparing scores on a video-game for math majors, writing majors, and psychology majors, we could run an ANOVA test with this line:

#+begin_src python
from scipy.stats import f_oneway
fstat, pval = f_oneway(scores_mathematicians, scores_writers, scores_psychologists)
#+end_src

If the p-value is below our significance threshold, we can conclude that at least one pair of our groups earned significantly different scores on average; however, we won’t know which pair until we investigate further!

**** Instructions
***** Task One
The same data from the previous exercise is available to you in the workspace: costs of sales made at three locations of VeryAnts (saved as a, b, and c).

Perform an ANOVA test on a, b, and c and store the p-value in a variable called pval, then print it out.

***** Task Two
At a .05 significance level, does this p-value lead you to reject the null hypothesis (and conclude that at least one pair of stores have significantly different average sales)?

Change the value of significant to True if the p-value indicates at least one pair of stores have significantly different sales and False otherwise.


#+begin_src python :results output
from scipy.stats import ttest_ind, f_oneway
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# store the data
veryants = pd.read_csv('veryants.csv')
a = veryants.Sale[veryants.Store == 'A']
b = veryants.Sale[veryants.Store == 'B']
c = veryants.Sale[veryants.Store == 'C']

# run t-tests
a_b_tval, a_b_pval = ttest_ind(a,b)
print(a_b_pval)
a_c_tval, a_c_pval = ttest_ind(a,c)
print(a_c_pval)
b_c_tval, b_c_pval = ttest_ind(b,c)
print(b_c_pval)

# determine significance
a_b_significant = True
a_c_significant = True
b_c_significant = False

#ANOVA
fstat, pval = f_oneway(a, b, c)
print("Anova: ", pval)

#ANOVA significance (True or False)
anova_significance = True

# create plot
sns.boxplot(data=veryants, x='Store', y='Sale')
plt.show()
#+end_src

#+RESULTS:
: 2.769886558708305e-05
: 0.02102938693149484
: 0.05986788486166067
: Anova:  0.00015355234908845413

