
* What is Calculus?

- Learn about what calculus is and how it is important in the field of data science.
      
The core task of a data scientist is to make data-driven recommendations on the best way to solve a problem. Along the way, data scientists build and fit statistical models to support their claims, make predictions, and more. In this article, we will look at what calculus is and why it is vital in the data science process.

** Rate of Change

      /Differential calculus/ is the field that studies rates of change. By quantifying how variables relate to each other, we can better understand our statistical model or physical system. For example, as a data scientist at a t-shirt company, we may want to know how a change in the marketing budget impacts the company’s total profit. Spend too little, and our product won’t be well known; spend too much, and we might reach a point of diminishing returns where our money would be better spent elsewhere. How can we find the optimal size of our marketing budget?

** Optimization

     The last question above is the sort of questions asked and answered by the field of /mathematical optimization/, which intertwines closely with calculus. Optimization problems involve looking for the best solution to a problem. Perhaps that’s finding the ‘optimal’ size of the marketing budget for our company, the point where we maximize our profits with a budget that allows us to reach a broad audience without paying too much. Perhaps that means finding the statistical model that ‘best’ fits our data according to some criteria that we define ourselves— mathematical optimization gives us a way to decide among all our possible options. It is a powerful field that underpins much of the modern machine learning revolution and it is built upon the fundamentals of calculus we will investigate.

**  Infinitesimal Analysis

     One of the fundamental paradigms in calculus is to think via /infinitesimals/ (extremely small quantities) to say things about instantaneous rates of change. We will discuss this at length in the upcoming lesson. To give a rough overview, however, the idea is that by ‘zooming in’ enough and considering how a variable changes over an infinitesimal time frame, we can learn how that variable is changing instantaneously, at a specific moment in time.

** Recap

    To recap, calculus is essential for a data scientist because it provides a foundation for mathematical optimization, a field used to tune machine learning models to classify and make predictions. With that in mind, let’s dive in. 

* Introduction to Differential Calculus

Data scientists often are asked to make data-driven recommendations on the best way to solve a problem. Along the way, they build and fit statistical models to support their claims, make predictions, and more. While creating these models, we often need to find the best solution out of all possible solutions, which is where calculus comes in.

Calculus gives us ways to determine how a response variable (like profit, or revenue, or click-through rate) changes with related independent variables (like gas prices, or click-through rate, or time). Understanding how independent variables change with respect to a response variable is essential for choosing an ideal model because it allows us to answer the following question: “what is the most effective model for our given situation?”

In this lesson, we will learn some fundamentals of calculus and gain some tools that data scientists use in their everyday jobs.

* Limits

The first concept we will look at is something called a limit. Limits quantify what happens to the values of a function as we approach a given point. This can be defined notationally as:

$$
\lim_{x\to\infty} f(x)
$$

We can read this in simple terms as “the limit as x goes to 6 of f(x) approaches some value L”. To evaluate this limit, we take points increasingly closer and closer to 6— as close to 6 as we can get, but not 6 itself! We then evaluate where the function is headed at those points.

If we look at the limit of a function as x approaches a value from one direction, this is called a one-sided limit. For example, we might look at the values of f(5), f(5.9), f(5.999) and see if they are trending towards the value of f(6). This is represented as:

$$
\lim_{x\to 6^{-}} f(x) = L
$$

We read this as “the limit as x approaches 6 from the left side approaches some value L.”

Whereas if we looked at the values of f(6.1), f(6.01), f(6.0005) and see if they are trending towards f(6), we would represent this as:

$$
\lim_{x\to 6^{+}} f(x) = L
$$

We read this as “the limit as x goes to 6 from the right side approaches some value L.”

This takes us to the final key concept about limits. The limit as x approaches 6 exists only if the limit as x approaches 6 from the left side is equal to the limit as x approaches 6 from the right side.

This is written out as:\\

if

$$
\lim_{x\to 6^{-}} f(x) = \lim_{x\to 6^{+}} f(x) = L
$$

then

$$
\lim_{x\to 6} f(x) = L
$$

if

$$
\lim_{x\to 6^{-}} f(x) \neq \lim_{x\to 6^{+}} f(x) = L
$$

then

$$
\lim_{x\to 6} f(x)\ does\ not\ exist
$$

* Limit Definition of a Derivative

Suppose we wanted to measure a runner’s instantaneous speed using a stopwatch. By instantaneous speed, we mean their speed at an exact moment in time.

Let’s define f(t) as the runner’s distance from the start time at time t. How could we find the runner’s instantaneous speed at 1 second after the race? We could record their positions at 1 second and some time after 1 second and then do some calculations. Let’s say we measure their distance from the start at f(1) and f(3). The change in position is f(3) - f(1), and the time between 1 second and 3 seconds is 2 seconds, so we can calculate the runner’s average speed to be the following:

$$
average\ speed = \frac{f(3) - f(1)}{3 - 1}
$$

However, this gives us the average speed, not the instantaneous speed. We don’t know the runner’s speed at t=1; we only know their speed on average over the 2-second interval.

If we repeated the process but instead took our second measurement at 1.1 seconds, we could be more accurate since we would find the average speed between 1 and 1.1 seconds. If we took our second measurement at a tiny increment, such as t=1.0000001, we would be *approaching* instantaneous speed and get a very accurate measurement. The animation to the right demonstrates this concept.

We can generalize this using limits. Define t = 1 to be the first measurement time, and let’s say we wait h seconds until taking the second measurement. Then the second time is x+h, and the positions at the two times are f(x) and f(x+h). Repeating the exact process as above, we define the runner’s average speed as:

$$
average\ speed = \frac{f(x +h) - f(x)}{(x + h) - x}
$$

Simplifies to:

$$
average\ speed = \frac{f(x +h) - f(x)}{h}
$$

Using limits, we can make h very small. By taking the limit as h goes to 0, we can find the instantaneous rate of change!

$$
instantaneous\ rate\ of\ change = \lim_{x\to 0} \frac{f(x + h) - f(x)}{h}
$$
