
* Welcome to the Data Scientist: Machine Learning Specialist Career Path
Your data science journey begins here!

Machine Learning is at the forefront of data science. It's what drives many od the technologies that we use every day, such as recommendation systems, disease identification, detectint credit card fraud, route optimization, and so much more. Collectively, these technologies represent a shitf in how data affects our dayly life.

** About the Data Scientist Career Paths
The Data Scientist Career Paths are designed for you to gain the knowledge, skills, and abilities (KSAs) you need to earn a data scientist job. You will develop the statistical knowledge, programming skills, and visualization techniques to work with data responsibly. You will also build a portfolio along the way to showcase your abilities to future employers.

You are currently enrolled in the Data Scientist: Machine Learning Specialist Career Path. Data Scientist who focus on machine learning specialize in supervised  and unsupervised machine learning, feature engineering, model evaluation, and answering data  problems at scale. As a Machine Learning based Data Scientist, you might work on a data science, product, marketing, or engineering team. You will often work to create predictive algorithms or identify anomalous activity.

This Career Path is divided into 2 parts. The firsts section covers all the basics every Data Scientist needs. We call this the Foundations of Data Science. The second section is the specialized KSAs you need to go from being a data generalist to a Data Scientist, Machine Learning Specialist.

If, after learning a bit more about data science, you decide that you’d like to change your specialty, your course progress will transfer, allowing you to pick up where you left off. (Note that Professional Certification exams will not transfer, as those have to be taken separately for each Professional Certification.) To learn more about the specialties, check out this blog post.

For a quick summary:

    - *Machine Learning Specialist* focus on Machine Learning, predictive analytics, creating models and algorithms, and answering questions at scale.

    - *Analytics Specialists* focus on answering questions with data, communicating results, and driving decision making.

    - *Inference Specialists* focus on finding out why something happened why causal inference, conducting hypothesis tests, and A/B test, and validating results statistically.

    - *Natural Language Processing Specialist* focus on getting meaning out of texts, generating human-like text, and interacting with computers for Artificial Intelligence.

** Overview
In the first half of this Career Path, you will learn about Python, SQL, statistics and data best practices. You will start with a code-free introduction to working with data in the Data Literacy Track and then dive into SQL and Python in the SQL fundamentals and Python Fundamentals Tracks. SQL and Python are essential tools that will give you the technical foundation you need to work with data programmatically.

Then you will dive into Data Manipulation with Python Pandas. Pandas is a Python library at the heart of Data Science. It is an essential tool for working with data and has dozens of useful built-in functions. Once you have mastered Pandas, you will apply your new programming skills to Exploratory Data Analysis where you will learn to summarize datasets before mastering the Fundamentals of Statistics where you will learn to spot trends and patterns.

Next, you will learn how to transform those numbers and analyses into meaningful Data Visualizations. Then you will apply your new skills to Wrangle and Tidy Datasets and prepare ral data for analysis. Finally, you will bring it all together to Communicate Data Science Findings to various groups and stakeholders.

At this point in your journey, you will have completed the Data Foundations and be ready to move into your specialty.

** Machine Learning Specialty
In the Machine Learning Specialty, you will learn about the most commonly used machine learning algorithms, when to apply them, and how to optimize them. You'll be able to leverage data to create predictive models, and analyze large datasets to derive new insights. Yo can apply your skills to solve a variety of business, medical, educational, and financial problems -machine learning is at the forefront of a wide variety of industries and organizations.

But, if you decide that you want to switch specialties after you learn more about Data Science, you can pick from any of our four specialties -and your progress will transfer!

By the end of the Data Scientist: Machine Learning Specialist Career Path, you will be able to:

    - Create programs with Python 3

    - Query and manipulate data with SQL and Python pandas

    - Create data visualizations wiht Python matplotlib and seaborn

    - Summarize and analyze datasets

    - Conduct hypothesis testing

    - Design experiments

    - Clean and tidy datasets

    - Built, train, and test supervised and unsupervised machine learning models

    - Evaluate model performance

    - Decide when to apply a given model

    - Conduct Feature Engineering

    - Leverage Jupyter Notebooks for experimentation and communication

Along the way, you will build a portfolio of projects to showcase your data scienc KSA's, and prove your job-ready skills!

** Syllabus Pages
We've created two types of syllabus pages to help guide you through this journey. You've already navigated to this article from the first type: The Career Path Syllabus.

You can use this Career Path Syllabus to see all the topics you'll need to know to become a Machine Learning Specialist -or as a tracker for what you've learned and will continue to learn. And from there, you can click on one of the topics listed on the right to access the second type of syllabus: the Unit Syllabus!

The Unit Syllabus is your go-to guide to your current Unit. Each Unit is a major topic that we teach using smaller chunks of content, and each Unit Syllabus contains expandable/collapsible list of all of those lessons, projects, and other content. We recommend looking at your current Unit Syllabus before you start coding for the day.

** Structure
Throughout this Path, you will see lessons, quizzes, articles, and projects. Lessons and articles introduce new tools and concepts, quizzes give you a chance to quickly check your understanding, and projects give you a chance to apply your new skills.

There are a lot of projects, but pay special attention to Portfolio Projects and Cumulative Projects because they give you a chance to apply your skills and build up your portfolio.

The content in this Career Path is cumulative, and we recommend that you take the courses in order. However, if you are familiar with a given technology or idea, feel free to jump ahead, but be aware that skipping modules will affect your completion percentage.

Finally, we are constantly updating our content to be sure it is up to date and of the highest quality. Keep an eye on the notification bells, which we will use to alert you to new content. Sometimes these updates might affect your completion.

* Certification Exams
We've added exams to help you assess your proficiency as you build toward job-ready skills. Here's how they work:

    - You'll find exams on your career path syllabus page at the end of each section.

    - Each exam assesses your knowledge of the concepts and technologies learned in that section. Exams help verify your proficiency -so you can feel confident in your abilities as you build toward a new career.

    - Each exam is 2 parts. The first is multiple choice and fill in the blank, and the second is coding questions, when applicable to the material. Otherwise, you will encounter additional multiple choice and fill in the blank questions.

    - Score at least 70% on both parts of the exam to pass.

    - If you don't pass, no worries! You can retake exams once every 24 hours.

    - Taking or passing exams is not required to complete the path and exams do not factor into your progress percentage. However, exams must be completed and passed to earn your Codecademy Professional Certification. That means, you can now skip past content you are already familiar with and still earn a Codecademy Professional Certification.

** Community
Finally, learning is social. Whatever you’re working on, be sure to connect with the Codecademy community in the forums. Remember to check in with the community regularly, including for things like asking for code reviews on your project work and providing code reviews to others in the projects category, which can help to reinforce what you’ve learned.
