
* Introduction
This project analyzes data from on-line dating application OKCupid. In recent years, there has been a massive rise in the usage of dating apps to find love. Many of these apps use sophisticated data science techniques to recommend possible matches to users and to optimize the user experience. These apps give us access to a wealth of information that we've never had before about how different people experience romance.

The goal of this project is to scope, prep, analyze, and create a machine learning model to solve a question.

Data sources:

~profiles.csv~ was provided by Codecademy.com.

* Scoping
It's beneficial to create a project scope whenever a new project is bein started. Below are four sections to help guide the project process and progress. The first section is the /project goals/, a section to define the high-level objetives and set the intentions for this project. The next section is the /data/, luckily in this project, data is already provided but still needs to be checked if project goals can be met with the available data. Thirdly, the /analysis/ will have to be thought through, which include the methods and aligning the question(s) with the project goals. Lastly, /evaluation/ will help build conclusions and findings from the analysis.

** Project Goals
In this project, the goal is to utilize the skills learned through Codecademy and apply machine learning techniques to a data set. The primary research question that will be answered is whether an OkCupid's user astrological sign can be predicted using other variables from their profiles. This project is important since many users find astrological signs an important part of matches, and if users don't input their sign, OkCupid would like to predict which sign they might be.

** Data
The project has one data set provided by Codecademy called ~profiles.csv~. In the data, each row represents an OkCupid user and the columns are the responses to their user profiles which include multi-choice and short answer questions.

** Analysis
This solution will use descriptive statistics and data visualization to find key figures in understanding the distribution, count, and relationship between variables. Since the goal of the project to make predictions on the user's astrological signs, classification algorithms from the supervised learning family of machine learning family of machine learning models will be implemented.

** Evaluation
The project will conclude with the evaluation of the machine learning model selected with a validation data set. The output of the predictions can be ckecked through a confusion matrix, and metrics such as accuracy, precision, recall, F1 and Kappa scores.

* Scrip.py

#+begin_src python :results output
  ## General libraries
  import numpy as np
  import pandas as pd
  from matplotlib import pyplot as plt
  import seaborn as sns

  plt.rcParams['figure.figsize'] = [6, 6]

  import warnings
  warnings.filterwarnings('ignore')

  profiles = pd.read_csv('profiles.csv', encoding='utf-8')
  print(profiles.head())

#+end_src

#+RESULTS:
:    age  ...     status
: 0   22  ...     single
: 1   35  ...     single
: 2   38  ...  available
: 3   23  ...     single
: 4   29  ...     single
:
: [5 rows x 31 columns]
