
* Classify Raisins with Hyperparameter Tuning Project
In this project, you'll use the different techniques you have learned in this unit to classify different types of raisins. The dataset has been posted on [[https://www.kaggle.com/datasets/muratkokludataset/raisin-dataset][Kaggle]] by [[https://www.muratkoklu.com/datasets/][Murat Koklu]], a researcher who has studied different raisin grain types [[https://dergipark.org.tr/tr/download/article-file/1227592][using machine learning methods]].

There are two raisin grain types in this dataset, Kecimen and Besni and seven numerical predictor variables associated with each of the 900 samples in the data. You're going to use this dataset to implement the two hyperparameter tuning methods we've covered in this module thus far:

    1. *Grid Search* method to tune a Decision Tree Classifier

    2. *Random Search* method to tune a Logistic Regression Classifier

You'll be using a Jupyter notebook to implement the project. At any point if you're away from the screen for too long, the Jupyter kernel might reset -so be sure to press Save on top of the notebook before taking a break!

** Explore the Dataset

*** Task 1
The dataset and some of the libraries you'll use have been loaded on the setup cell. Run the setup cell to get started!

*** Task 2
Create the predictor and target variables and label them X and y respectively.

*Hint*
The column ~'Class'~ represents the target variable ~y~ and the rest of the columns together compose the predictor variable matrix ~X~.

*** Task 3
Examine the dataset by printing the

    - total number of features
    - total number of samples
    - samples belonging to class '1'

*Hint*
    - The number of columns in X corresponds the number of features
    - The length of ~X~ or ~y~ give us the total number of raisins in the dataset
    - The sum of the target variable column is an easy way to get the number of samples belonging to class '1'

*** Task 4
Split the training data into train and test data with a random_state of 19 (if you want to match the solution code -you're welcome to use your preferred random_state too! Label the training data X_train and y_train and test data, X_test and y_test.

** Grid Search with Decision Tree Classifier

*** Task 5
A decision tree classifier works well for a binary balanced class classification problem. Initialize a decision tree classifier named ~tree~.

*Hint*
Use scikit-learn's DecisionTreeClassifier().

*** Task 6
The DecisionTreeClassifier() implementation in scikit-learn has many parameters.

Create a dictionary parameters to set up grid search to explore three values each for the followin 2 hyperparameters:

    - ~'max_depth'~ : The maximum tree depth; explore the values 3, 5 and 7 for this.

    - ~'min_samples_split'~ : The minimum number of samples to split at each node; explore the values 2, 3 and 4 for this.

*** Task 7
Create a grid search classifier ~grid~ with ~tree~ and ~parameters~ as inputs. Fit the grid search classifier to the training data.

*** Task 8
Use the ~.best_estimator_~ attribute to see what hyperparameters grid chose. Print the result. Print the best score and the score on the test data to examine the performance of the best estimator.

*** Task 9
Use ~.cv_results_['mean_test_score']~ to get the score for each hyperparameter combination. Get the corresponding hyperparameters with ~.cv_results_['params']~.

Convert the two arrays to DataFrames, concatenate them using ~pd.concat~ and print it to view the score for each hyperparameter combination.

** Random Search with Logistic Regression

*** Task 10
Define a logistic regression model, ~lr~, with ~solver~ set to ~'liblinear'~ and ~max_iter = 1000~.

*** Task 11
To perform random search we need to specify the parameters and the distributions to draw from. Define a dictionary ~distributions~ with the keys

    - ~'penalty'~ : corresponding to the type of regularization to apply. Choose a discrete distribution with 'l1' and 'l2'.

    - ~'C'~ : corresponding to the regularization strength. Choose a uniform distribution here between 0 and 100.

*Hint*
Import uniform from scipy.stats to access a uniform distribution. You can use parameters loc and scale to obtain a uniform distribution on [loc, loc+scale].

*** Task 12
Create a model named ~clf~ to perform random search with the logistic regression model you've defined, over the distribution space specified by ~distributions~ and for eight random draws. Fit the model to the training data.

*Hint*
Use scikit-learn's RandomizedSearchCV model with parameters lr, distributions and n_iter=8.

*** Task 13
Print the best estimator and score from the random search you've performed. Print a table summarizing the results using .cv_results_ similar to the way you did for grid search!




** Script.py

#+begin_src python :results output
  # 1. Setup
  import pandas as pd
  from sklearn.model_selection import train_test_split
  from sklearn.tree import DecisionTreeClassifier
  from sklearn.linear_model import LogisticRegression
  from sklearn.model_selection import GridSearchCV
  from sklearn.model_selection import RandomizedSearchCV

  # Load data as xlsx
  raisins = pd.read_excel('Raisin_Dataset.xlsx')
  print(raisins.head())

  # Recode class to binary
  raisins['Class'] = raisins['Class'].replace({'Kecimen': 0, 'Besni': 1})

  # 2. Create predictor and target variables, X and y
  y = raisins['Class']
  X = raisins.drop(columns = ['Class'], axis = 1)

  # 3. Examine the dataset
  print('Number of features:', X.shape[1])
  print('Number of samples:', len(y))
  print("Samples belonging to class '1':", y.sum())

  # 4. Split the data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=19)

  # 5. Create a Decision Tree model
  tree = DecisionTreeClassifier()

  # 6. Dictionary of parameters for GridSearchCV
  parameters = {'max_depth': [3, 5, 7], 'min_samples_split': [2, 3, 4]}

  # 7.1 Create a GridSearchCV model
  grid = GridSearchCV(tree, parameters)

  # 7.2 Fit the GridSearchCV model to the training data
  grid.fit(X_train, y_train)

  # 8.1 Print the model and hyperparameters obtained by GridSearchCV
  print(grid.best_estimator_)

  # 8.2 Print best score
  print(grid.best_score_)

  # 8.3 Print the accuracy of the final model on the test data
  print(grid.score(X_test, y_test))

  # 9. Print a table summarizing the results of GridSearchCV
  df = pd.concat([pd.DataFrame(grid.cv_results_['params']), pd.DataFrame(grid.cv_results_['mean_test_score'], columns=['score'])], axis=1)
  print(df)

  # 10. The logistic regression model
  lr = LogisticRegression(solver='liblinear', max_iter=1000)

  # 11. Define distributions to choose hyperparameters from
  from scipy.stats import uniform
  distributions = {'penalty':['l1', 'l2'], 'C':uniform(loc=0, scale=100)}

  # 12.1 Create a RandomizedSearchCV model
  clf = RandomizedSearchCV(lr, distributions, n_iter=8)

  # 12.2 Fit the model to the training data
  clf.fit(X_train, y_train)

  # 13.1 Print best estimator and best score
  print(clf.best_estimator_)
  print(clf.best_score_)

  # 13.1 Print a table summarizing the results of RandomSearchCV
  df = pd.concat([pd.DataFrame(clf.cv_results_['params']), pd.DataFrame(clf.cv_results_['mean_test_score'], columns=['Accuracy'])] ,axis=1)
  print(df.sort_values('Accuracy', ascending = False))

#+end_src

#+RESULTS:
#+begin_example
    Area  MajorAxisLength  MinorAxisLength  ...    Extent  Perimeter    Class
0  87524       442.246011       253.291155  ...  0.758651   1184.040  Kecimen
1  75166       406.690687       243.032436  ...  0.684130   1121.786  Kecimen
2  90856       442.267048       266.328318  ...  0.637613   1208.575  Kecimen
3  45928       286.540559       208.760042  ...  0.699599    844.162  Kecimen
4  79408       352.190770       290.827533  ...  0.792772   1073.251  Kecimen

[5 rows x 8 columns]
Number of features: 7
Number of samples: 900
Samples belonging to class '1': 450
DecisionTreeClassifier(max_depth=5)
0.8681481481481482
0.8177777777777778
   max_depth  min_samples_split     score
0          3                  2  0.859259
1          3                  3  0.862222
2          3                  4  0.860741
3          5                  2  0.868148
4          5                  3  0.868148
5          5                  4  0.866667
6          7                  2  0.845926
7          7                  3  0.842963
8          7                  4  0.842963
LogisticRegression(C=45.62459801640283, max_iter=1000, penalty='l1',
                   solver='liblinear')
0.8755555555555556
           C penalty  Accuracy
0  45.624598      l1  0.875556
4  47.723666      l1  0.875556
3  15.215743      l2  0.875556
5  22.865003      l2  0.875556
1  98.354423      l1  0.874074
2   4.214664      l2  0.874074
6  93.751095      l2  0.874074
7  39.587819      l2  0.874074
#+end_example
